<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="105133" started-at="2017-03-16T06:47:43Z" finished-at="2017-03-16T06:49:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="105133" started-at="2017-03-16T06:47:43Z" finished-at="2017-03-16T06:49:28Z">
      <class name="com.indeed.tests.DataDrivenTesting">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="setup" is-config="true" duration-ms="43806" started-at="2017-03-16T12:17:48Z" finished-at="2017-03-16T12:18:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="doLogin" duration-ms="11778" started-at="2017-03-16T12:18:31Z" data-provider="getData" finished-at="2017-03-16T12:18:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user unable to login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user unable to login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.indeed.tests.DataDrivenTesting.doLogin(DataDrivenTesting.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="QuitTC()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="QuitTC" is-config="true" duration-ms="13261" started-at="2017-03-16T12:18:43Z" finished-at="2017-03-16T12:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitTC -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="setup" is-config="true" duration-ms="5995" started-at="2017-03-16T12:18:57Z" finished-at="2017-03-16T12:19:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="doLogin" duration-ms="12120" started-at="2017-03-16T12:19:03Z" data-provider="getData" finished-at="2017-03-16T12:19:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="QuitTC()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="QuitTC" is-config="true" duration-ms="1365" started-at="2017-03-16T12:19:15Z" finished-at="2017-03-16T12:19:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitTC -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="setup" is-config="true" duration-ms="5635" started-at="2017-03-16T12:19:16Z" finished-at="2017-03-16T12:19:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="doLogin" duration-ms="5326" started-at="2017-03-16T12:19:22Z" data-provider="getData" finished-at="2017-03-16T12:19:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[user3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user unable to login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user unable to login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.indeed.tests.DataDrivenTesting.doLogin(DataDrivenTesting.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="QuitTC()[pri:0, instance:com.indeed.tests.DataDrivenTesting@62ee68d8]" name="QuitTC" is-config="true" duration-ms="1486" started-at="2017-03-16T12:19:27Z" finished-at="2017-03-16T12:19:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitTC -->
      </class> <!-- com.indeed.tests.DataDrivenTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
